"""IventoryUser added report_id

Revision ID: 68077c6ef98b
Revises: 05848a9b0a48
Create Date: 2025-09-04 16:07:50.831139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68077c6ef98b'
down_revision: Union[str, None] = '05848a9b0a48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_users', sa.Column('report_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'inventory_users', 'reports', ['report_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_users', type_='foreignkey')
    op.drop_column('inventory_users', 'report_id')
    # ### end Alembic commands ###
